language: php

php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - REPORT_EXIT_STATUS=1 NO_INTERACTION=1

script: phpize && ./configure && make && make test

notifications:
  email:
    - reeze.xia@gmail.com
